Upload config file, environment file, Dockerfile file
logzio/otel-docker-collector-metrics pull request #2
Opened 2022-01-12 09:01 UTC by resdenia

2022-01-12 09:21 UTC, yotamloe requested changes
Looks good, few notes:
* Please add draft `README.md` for Nico
* The otel receiver has more configuration options. I think we should add at least `excluded_images` option for our users. [ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/dockerstatsreceiver#configuration)
* A question: This project will handle more modules in the future? Or its designed only for docker metrics?

2022-01-12 09:32 UTC, mirii1994 requested changes
Great work, please see my comments.
Please have @nico-shishkin go over the documentation.

2022-01-12 09:32 UTC, mirii1994 commented on README.md
> +
Please remove this section. User should use this image without cloning the repo, just by pulling the docker image and then run it.

2022-01-12 09:32 UTC, mirii1994 commented on README.md
> +```
Remove this part, user should use it by pulling the image, not cloning & building locally :)

2022-01-12 09:32 UTC, mirii1994 commented on README.md
> +
Please add a changelog section

2022-01-12 09:46 UTC, resdenia commented on README.md
> +
Added Versions

2022-01-12 09:46 UTC, resdenia commented on README.md
> +
Removed

2022-01-13 12:16 UTC, nico-shishkin approved these changes

2022-01-13 12:29 UTC, Doron-Bargo requested changes

2022-01-13 12:29 UTC, Doron-Bargo commented on README.md
>  To simplify shipping metrics from one or many sources, we created Docker Metrics Collector. Docker Metrics Collector is a container that runs Metricbeat with the modules you enable at runtime.
What is the connection for metricbeat?

2022-01-17 14:51 UTC, mirii1994 requested changes

2022-01-17 14:51 UTC, mirii1994 commented on .gitignore
>  app.py
I think there isn't an "app.py" file in this repo, so maybe remove it?

2022-01-17 14:51 UTC, mirii1994 commented on Dockerfile
> +COPY app.py ./
Did not see `app.py` in the repo.

2022-01-17 14:51 UTC, mirii1994 commented on Dockerfile-arm
> +COPY app.py ./
Did not see app.py in the repo.

2022-01-17 19:19 UTC, Doron-Bargo requested changes
Hi , please see my comments

2022-01-17 19:19 UTC, Doron-Bargo commented on README.md
>  in the left menu.
Please remove this entire paragraph : 
"...Give your metrics a few minutes to get from your system to ours,
and then open [Logz.io](https://app.logz.io/#/dashboard/kibana).
You can view your metrics in Grafana.
We offer preconfigured dashboards for several sources,
which you can find by clicking **<i class="fas fa-th-large"></i> > Manage**
in the left menu...."
and replace it with : 
"Give your data some time to get from your system to ours, then log in to your Logz.io Metrics account, and open the Logz.io Metrics tab ( and link to https://app.logz.io/#/dashboard/metrics/).

2022-01-17 19:19 UTC, Doron-Bargo commented on README.md
>   --env DOCKER_ENDPOINT="<<DOCKER_ENDPOINT>>" \
This parameter should be optional (with default unix:///var/run/docker.sock ) and therefore not listed here. Also the python code should check if it the user use it and update accordingly

2022-01-17 19:19 UTC, Doron-Bargo commented on README.md
>   --env COLLECTION_INTERVAL="<<COLLECTION_INTERVAL>>" \
This parameter should be optional (with default 30s) and therefore not listed here. Also the python code should check if it the user use it and update accordingly

2022-01-17 20:04 UTC, Doron-Bargo commented on config.yaml
> +    - pubsub
why we have this section and these images

2022-01-17 20:05 UTC, Doron-Bargo requested changes

2022-01-17 20:05 UTC, Doron-Bargo commented on README.md
> +## Versions
Also please state how should the metrics will look like so it will be easy to look for them

2022-01-23 09:49 UTC, mirii1994 requested changes
When I tried to run the current image got this error:
```sh
Traceback (most recent call last):
  File "//app.py", line 36, in <module>
    w.store_array_in_yaml()
  File "//app.py", line 14, in store_array_in_yaml
    config('EXCLUDED_IMAGES'))
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 70, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: EXCLUDED_IMAGES not found. Declare it as envvar or define a default value.
```
The user shouldn't be required to use/define EXCLUDED_IMAGES

2022-01-23 09:49 UTC, mirii1994 commented on README.md
> + -v $(pwd)/config.yaml:/config.yaml \
Why do we need this: `-v $(pwd)/config.yaml:/config.yaml`?
The docker file copies it as default, only if someone wants to mount its own config he should use this command, I don't think it should be in the command

2022-01-23 09:49 UTC, mirii1994 commented on README.md
> + logzio/otel-docker-collector-metrics:latest
The name in this command does not match the name from the docker pull command.

2022-01-23 10:07 UTC, mirii1994 commented on app.py
> +        excluded_images = ast.literal_eval(
Why not use os.environ?

2022-01-24 19:48 UTC, Doron-Bargo requested changes
Please see my comments

2022-01-24 19:48 UTC, Doron-Bargo commented on README.md
> +## Versions
@resdenia - what about this issue?

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +            os.environ['EXCLUDED_IMAGES'])
The parameters' table in Readme missing the EXCLUED_IMAGES parameter
Please add to the table, and explain on how to use this environment variable

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +        if 'DOCKER_ENDPOINT' in os.environ:
Should be TIMEOUT and not DOCKER_POINT

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +            timeout = '5s'
In the Readme you wrote that the default value for timeout is 30s but here is 5s . Which one is the correct one?
Please fix

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +                if not 'excluded_images' in config_data:
Why do you have this condition? 
If i understand correct you update the collection_interval, endpoint and timeout only if customer decide not to use excluded_images?
What happen if he decide that he want to exclude images and change those parameters

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +                    if not 'excluded_images' in config_data:
Why you need this condition ?
If customer decide to use excluded_images and for some reason the config already have it shouldnt we overwrite the config with the new parameter?

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +        if 'COLLECTION_INTERVAL' in os.environ:
better use os.getenv(key, default = None) instead the if condition

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +        if 'DOCKER_ENDPOINT' in os.environ:
better use os.getenv(key, default = None) instead the if condition

2022-01-24 19:48 UTC, Doron-Bargo commented on app.py
> +        if 'DOCKER_ENDPOINT' in os.environ:
better use os.getenv(key, default = None) instead the if condition

2023-09-12 07:36 UTC, closed without merging